### ISSUE TITLE
$GOPATH not set OSX

### ISSUE THREAD

**Issue by ozkar99** [joefitzgerald/go-get#9]
says $GOPATH is not set, when it is.
I am running osx

$ uname -a:
`Darwin kaze.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64`

$ atom -v:
`1.6.1`

please let me know if you need anything else.

**Comment by ozkar99** [comment]
Seems like it only happens when i run atom from tmux.

This issue is probably for go-config, not the go-get package.

will try to fix.

**Comment by ozkar99** [comment]
Closing since this is already documented, sorry for this.

**Comment by ozkar99** [comment]
ftr:

My problem was that tmux was reporting an incorrect $SHELL  (bash, when using zsh) and that seem's to break the atom environment package.

**Comment by hasit** [comment]
I still have this issue on OSX. I am not using tmux. This only happens when I run Atom from /Applications and not when I run it from the command line like `atom .`, `atom --add`, or 'atom`.

As you can see in the following picture, Atom tells me that I need to update two packages:
<img width="470" alt="screen shot 2016-04-20 at 2 04 57 pm" src="https://cloud.githubusercontent.com/assets/1553055/14690529/5e011546-0701-11e6-8961-450ca9bb1b98.png">

When I click on that button, it shows me these errors.
<img width="461" alt="screen shot 2016-04-20 at 2 05 11 pm" src="https://cloud.githubusercontent.com/assets/1553055/14690530/5f5df652-0701-11e6-89aa-1a187fb71e9d.png">

I can confirm that I have set `$GOPATH` by typing `go env` in terminal. Here is the output:

```
Last login: Wed Apr 20 13:04:47 on ttys000
~ $ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hasitmistry/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

Please do reopen the issue.
